# Generated by Django 2.2.2 on 2019-06-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('urlprefix', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dom_db',
            },
        ),
        migrations.CreateModel(
            name='Dbxref',
            fields=[
                ('dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_genome_domestication.Db')),
            ],
            options={
                'db_table': 'dom_dbxref',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('uniquename', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('species', models.CharField(max_length=255)),
                ('residues', models.TextField()),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_genome_domestication.Dbxref')),
            ],
            options={
                'db_table': 'dom_feature',
            },
        ),
        migrations.CreateModel(
            name='FeatureDbxref',
            fields=[
                ('feature_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_genome_domestication.Dbxref')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_genome_domestication.Feature')),
            ],
            options={
                'db_table': 'dom_featdbxref',
            },
        ),
    ]
