# Generated by Django 2.2.9 on 2020-01-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('count_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'cv',
            },
        ),
        migrations.CreateModel(
            name='Cvterm',
            fields=[
                ('cvterm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('definition', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cv')),
            ],
            options={
                'db_table': 'cvterm',
            },
        ),
        migrations.CreateModel(
            name='Db',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('urlprefix', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'db',
            },
        ),
        migrations.CreateModel(
            name='Dbxref',
            fields=[
                ('dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Db')),
            ],
            options={
                'db_table': 'dbxref',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('uniquename', models.CharField(max_length=255, unique=True)),
                ('chasis_1', models.CharField(max_length=255)),
                ('chasis_2', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3000)),
                ('timecreation', models.DateTimeField(auto_now_add=True)),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Dbxref')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cvterm')),
            ],
            options={
                'db_table': 'experiment',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('uniquename', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('residues', models.TextField()),
                ('prefix', models.CharField(max_length=4)),
                ('suffix', models.CharField(max_length=4)),
                ('genbank_file', models.FileField(upload_to='genbank')),
                ('timecreation', models.DateTimeField(auto_now_add=True)),
                ('timelastmodified', models.DateTimeField(auto_now=True)),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Dbxref')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cvterm')),
                ('vector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goldenbraid.Feature')),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Stockcollection',
            fields=[
                ('stockcollection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uniquename', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Contact')),
            ],
            options={
                'db_table': 'stockcollection',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uniquename', models.TextField()),
                ('description', models.TextField()),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='goldenbraid.Feature')),
                ('stockcollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Stockcollection')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='FeatureRelationship',
            fields=[
                ('featurerelationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='goldenbraid.Feature')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='goldenbraid.Feature')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cvterm')),
            ],
            options={
                'db_table': 'feature_relationship',
            },
        ),
        migrations.CreateModel(
            name='Featureprop',
            fields=[
                ('featureprop_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('rank', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Feature')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cvterm')),
            ],
            options={
                'db_table': 'featureprop',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPropText',
            fields=[
                ('experiment_prop_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.TextField(max_length=3000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
            ],
            options={
                'db_table': 'experimentproptext',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPropNumeric',
            fields=[
                ('experiment_prop_numeric_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Cvterm')),
            ],
            options={
                'db_table': 'experimentpropnumeric',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPropImage',
            fields=[
                ('experiment_prop_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='result_files')),
                ('description', models.CharField(max_length=255)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
            ],
            options={
                'db_table': 'experimentpropimage',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPropGenericFile',
            fields=[
                ('experiment_prop_generic_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='result_files')),
                ('description', models.CharField(max_length=255)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
            ],
            options={
                'db_table': 'experimentpropgenericfile',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPropExcel',
            fields=[
                ('experiment_prop_excel_id', models.AutoField(primary_key=True, serialize=False)),
                ('excel', models.FileField(upload_to='result_files')),
                ('description', models.CharField(max_length=255)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
            ],
            options={
                'db_table': 'experimentpropexcel',
            },
        ),
        migrations.CreateModel(
            name='ExperimentKeyword',
            fields=[
                ('experiment_keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
            ],
            options={
                'db_table': 'experimentkeyword',
            },
        ),
        migrations.CreateModel(
            name='FeaturePerm',
            fields=[
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='goldenbraid.Feature')),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'featureperm',
            },
        ),
        migrations.CreateModel(
            name='ExperimentSubFeature',
            fields=[
                ('experiment_key_subfeature_id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Feature')),
            ],
            options={
                'db_table': 'experimentkeysubfeature',
                'unique_together': {('experiment', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentPerm',
            fields=[
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='goldenbraid.Experiment')),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experimentperm',
            },
        ),
        migrations.CreateModel(
            name='ExperimentFeature',
            fields=[
                ('experiment_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Experiment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenbraid.Feature')),
            ],
            options={
                'db_table': 'experimentfeature',
                'unique_together': {('experiment', 'feature')},
            },
        ),
    ]
