VECTOR_TYPE_NAME = 'Vector'
ENZYME_TYPE_NAME = 'Enzyme'
DESCRIPTION_TYPE_NAME = 'Description'
ENZYME_IN_TYPE_NAME = 'Enzyme_in'
ENZYME_OUT_TYPE_NAME = 'Enzyme_out'
GOLDEN_DB = 'goldenbraid'
GOLDEN_CV = 'goldenbraid'
